### ISSUE TITLE
Should not hold OptionalEntity on BsEntity

### ISSUE THREAD

**Issue by taktos** [dbflute/dbflute-core#25]
DBFlute-1.1で、BsEntityの関連テーブルフィールドの型が `OptionalEntity<RELATION>` になっています。
BsEntityはSerializableである一方、OptionalEntity（またはjava.util.Optional）はそうではありません。
（そもそもEntityが本当にSerializableなのか？というのもあるのですが・・・ :sweat_smile:

BsEntityではRELATIONエンティティの型のままフィールドで保持し、ゲッターで `return Optiona.ofNullable(relation)` とするべきではないでしょうか。

> Java8のOptionalがSerializableではない理由については、[このコメント](http://stackoverflow.com/a/24564612) やそこからリンクされている [このスレッド](http://mail.openjdk.java.net/pipermail/jdk8-dev/2013-September/003274.html) 辺りがとても参考になりました。

**Comment by dbflute** [comment]
なるほど、ありがとう。
そうだねぇ、EntityのSerializableが成り立ってるかは微妙だね。
CB はどこかのタイミングで外したけど。

EntityのRelationのOptionalは、気軽に何度getされてもnewしないようにってしてるんだけど、まあそんなケースはそんなにないだろうし、EmptyのRelationならなおさら少ないから気にしなくていいレベルではあるけどね。とはいえ、ソース読んでもらったときにシンプルな方が印象良いかなってところで特に困らなければOptionalごと持つようにしたという感じ。

ちょっと、どのみちよいきっかけなので、
少しSerializable検証して、どっちかを直すようにします。

**Comment by dbflute** [comment]
いまSerializeすると…
　o 基点テーブルだけなら: OK
　o 関連テーブルが入ると: NG (例外発生)
　o DerivedMapの中にSerializableじゃないものが入ると: NG

ということで、できるところまでSerializeするって感じのようだ。
DerivedMapは気にしなくてもいいけど、
関連テーブルが入るとできないっていう中途半端な状態。

関連テーブルをPlainで保持してgetでOptionalで戻すとなると、
Setterがplainで、GetterがOptionalってことになるので、
Beanのルールとして変になるのでうまく動かないような気がする。
というか、それがあったので Optional を保持するようにした経緯があった(ような)。
回避できなくはないのかもしれないけど大工事+互換崩しになりそうなので、
保持形式をplainにする(厳密にはSetterをplainにする)のはちょっと厳しい。

A. Serializeを外す => 若干の互換を崩す、ExEntityに取り残されたSerialIDの警告がつらい
B. transientを付ける => 関連テーブルあってもエラーにならないのが逆にわかりづらいかも!?
C. いまのまま => 関連テーブルあるとエラーになる、将来のチャンスを伺う
D. OptionalEntityだけSerializableに => 少しの工事でできなくもないかも!?

参考のURLでOptionalはSerializableにするものじゃないとあるけど、
Entity (JavaBeans) のようなものでどうあるべきかってまた難しい問題な気がする。
少なくとも、OptionalEntityはEntity専用の特別なOptionalなので、
DBFluteとしてはどちらかというと Serializable にしちゃう方がいいのかなって。

ちょっと、D or A or C を検討しています。
D がダメなら A か C。

**Comment by taktos** [comment]
> 関連テーブルをPlainで保持してgetでOptionalで戻すとなると、
> Setterがplainで、GetterがOptionalってことになるので、
> Beanのルールとして変になるのでうまく動かないような気がする。
そしたら、SetterもOptionalを受け取る（現状のまま）にするのはどうでしょう？

```java
public void setMemberStatus(OptionalEntity<MemberStatus> rel) {
    if (rel == null) return;
    rel.ifPresent(r -> this.memberStatus = rel.get());
}
```

Getter/Setterの型が一致していればJavaBeans規約的にOKのはずですし、1.1.0-sp2以前とも互換が取れます。

**Comment by dbflute** [comment]
ありがとう。
ただ、OptionalEntityに例外情報をのっけているので、
取り出しちゃうとその情報がなくなっちゃうんだよね。
(すると、そもそもOptionalEntityの意味がなくなっちゃうので、
どちらかというと保持をしたいという感じで)

とりありず、OptionalEntityだけは特別にSerializableにしました。
OptionalEntityは用途が限定的なので影響ないだろうということで。

Java8 の Optional モードだったら保持せずに処理する、
って分岐ができればいいのかもね。
そもそも、Java8 Optionalモードって動くかな？？？
(自動生成は動いても実際にマッピングされるかどうか...)

**Comment by taktos** [comment]
OptionalEntityに状態を持っているのですね。。そうすると状態が失われるのはイマイチですね。

とりあえず、以下の修正でOptionalモードで動くようになりました。

1. littleAdjustmemtMap.dfpropで `basicOptionalEntityClass`と`relationOptionalEntityClass`に`java.util.Optional`を指定
2. BaseEntity.vmで関連テーブルのExEntityを保持しつつ、getter/setterではOptional使うよう修正
3. BaseBhv.vmで`doSelectXXX`の`createOptionalEntity`を`Optional.ofNullable`に修正
4. ImplementedInvokerAssistant.java の `RelationOptionalFactory newRelationOptionalFactory()`をオーバーライド

出来上がったBsEntity.javaとExtendedImplementedInvokerAssistant.javaはこんな感じです。

```java
    /** MEMBER_STATUS by my MEMBER_STATUS_CODE, named 'memberStatus'. */
    protected MemberStatus _memberStatus;

    /**
     * [get] MEMBER_STATUS by my MEMBER_STATUS_CODE, named 'memberStatus'. <br>
     * Optional: alwaysPresent(), ifPresent().orElse(), get(), ...
     * @return The entity of foreign property 'memberStatus'. (NotNull, EmptyAllowed: when e.g. null FK column, no setupSelect)
     */
    public Optional<MemberStatus> getMemberStatus() {
        return Optional.ofNullable(_memberStatus);
    }

    /**
     * [set] MEMBER_STATUS by my MEMBER_STATUS_CODE, named 'memberStatus'.
     * @param memberStatus The entity of foreign property 'memberStatus'. (NullAllowed)
     */
    public void setMemberStatus(Optional<MemberStatus> memberStatus) {
        if (memberStatus == null) { _memberStatus = null; return; }
        _memberStatus = memberStatus.orElse(null);
    }
```

```java
public class ExtendedImplementedInvokerAssistant extends ImplementedInvokerAssistant {
	protected RelationOptionalFactory newRelationOptionalFactory() {
		return new RelationOptionalFactory() {
			@Override
			public Object createOptionalNullEntity(
					OptionalThingExceptionThrower thrower) {
				return Optional.empty();
			}
			@Override
			public Object createOptionalPresentEntity(Object relationRow) {
				return Optional.of(relationRow);
			}
			@Override
			public Class<?> getOptionalEntityType() {
				return Optional.class;
			}
			@Override
			public Object orElseNull(Object optional) {
				return ((Optional<?>) optional).orElse(null);
			}
		};
	}
}
```

この修正で、以下のSerialize/Deserializeのテストも通りました。

```java
	@Test
	public void testSerialize() throws Exception {
		Member member = memberBhv.selectEntityWithDeletedCheck(cb -> {
			cb.setupSelect_MemberStatus();
			cb.query().setMemberId_Equal(1);
		});

		assertThat(member.getMemberStatus().isPresent(), is(true));
		assertThat(member.getMemberServiceAsOne().isPresent(), is(false));

		ByteArrayOutputStream out = new ByteArrayOutputStream();
		ObjectOutputStream oos = new ObjectOutputStream(out);
		oos.writeObject(member);

		ObjectInputStream oin = new ObjectInputStream(new ByteArrayInputStream(out.toByteArray()));
		Member deserialized = (Member) oin.readObject();

		assertThat(deserialized.getMemberStatus().isPresent(), is(true));
		assertThat(deserialized.getMemberServiceAsOne().isPresent(), is(false));

		assertThat(member.getMemberId(), is(deserialized.getMemberId()));
		assertThat(member.getMemberStatus().get().getMemberStatusCode(), is(deserialized.getMemberStatus().get().getMemberStatusCode()));
	}
```

**Comment by dbflute** [comment]
> とりあえず、以下の修正でOptionalモードで動くようになりました。
情報ありがとう。

デフォルトでは、Serializable な OptionalEntity で、
Java8標準を使うとしたらそのやり方という感じで。

**Comment by jflute** [comment]
closeし忘れてたのでclose
